### ISSUE TITLE
c++ error while importing 

### ISSUE THREAD

**Issue by sennosays** [stevengj/Cubature.jl#11]
Hi, 

I recently upgraded to Julia version 0.4.0 on my Mac running OS X Yosemite Version 10.10.5. I was able to add the package Cubature with no problems but when I try to import it: 

using Cubature 

I get the following error and Julia crashes: 

julia> using Cubature
Assertion failed: (ctx->gensym_assigned.at(idx)), function emit_expr, file codegen.cpp, line 3130.

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Abort trap: 6

Because I believe this may be a C/C++ complier error I've attached the information regarding gcc/g++ 

Tyche: ~/Research/notebooks $ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

Tyche: ~/Research/notebooks $ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

Is this a known issue? Have I not upgraded some important software?

**Comment by stevengj** [comment]
I just tried it with MacOS 10.11.1 and it works fine for me.  Your compiler shouldn't matter, because `Pkg.build("Cubature")` downloads a precompiled binary of the library.   Unless you built Julia from source rather than downloading the binary?

**Comment by stevengj** [comment]
What is the output of `versioninfo(true)` in Julia?

**Comment by sennosays** [comment]
julia> versioninfo(true)

Julia Version 0.4.0

Commit 0ff703b* (2015-10-08 06:20 UTC)

Platform Info:

  System: Darwin (x86_64-apple-darwin14.5.0)

  CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz

  WORD_SIZE: 64

  uname: Darwin 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09
PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64 i386

Memory: 16.0 GB (10895.609375 MB free)

Uptime: 165.0 sec

Load Avg:  5.373046875  4.49658203125  2.02685546875

Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz:

       speed         user         nice          sys         idle
irq

#1  2500 MHz        634 s          0 s        262 s        775 s          0
s

#2  2500 MHz        397 s          0 s        134 s       1130 s          0
s

#3  2500 MHz        600 s          0 s        232 s        829 s          0
s

#4  2500 MHz        395 s          0 s        138 s       1129 s          0
s


  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)

  LAPACK: libopenblas

  LIBM: libopenlibm

  LLVM: libLLVM-3.3

Environment:

  TERM = xterm-256color

  PATH =
/Users/nicholassenno/anaconda/bin:/Users/nicholassenno/.local/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/Library/TeX/texbin

  XPC_FLAGS = 0x0

  HOME = /Users/nicholassenno


Package Directory: /Users/nicholassenno/.julia/v0.4

3 required packages:

 - Cubature                      1.0.9

 - IJulia                        1.1.8

 - PyPlot                        2.1.1

16 additional packages:

 - BinDeps                       0.3.19

 - ColorTypes                    0.2.0

 - Colors                        0.6.0

 - Compat                        0.7.7

 - Conda                         0.1.8

 - Dates                         0.4.4

 - FixedPointNumbers             0.1.1

 - Homebrew                      0.1.17

 - JSON                          0.5.0

 - LaTeXStrings                  0.1.6

 - Nettle                        0.2.0

 - PyCall                        1.1.2

 - Reexport                      0.0.3

 - SHA                           0.1.2

 - URIParser                     0.1.1

 - ZMQ                           0.3.0

**Comment by stevengj** [comment]
Can you try:
```jl
rm(Pkg.dir("Cubature","deps","libcubature.dylib"))
rm(Pkg.dir("Cubature","deps","installed_vers"))
Pkg.build("Cubature")
Pkg.test("Cubature")
```
to force it to re-download the library?

**Comment by sennosays** [comment]
I tried your suggestion but it produced the same error.

I ended up removing julia and cloning the source from git. Afterwards the
problem went away.

On Wed, Nov 4, 2015 at 12:51 PM, Steven G. Johnson <notifications@github.com
> wrote:

> Can you try:
>
> rm(Pkg.dir("Cubature","deps","libcubature.dylib"))rm(Pkg.dir("Cubature","deps","installed_vers"))
> Pkg.build("Cubature")
> Pkg.test("Cubature")
>
> to force it to re-download the library?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevengj/Cubature.jl/issues/11#issuecomment-153808046>
> .
>



-- 
Ph.D. candidate
532C Davey Laboratory
Physics Department
Eberly College of Science
The Pennsylvania State University
