### ISSUE TITLE
Installation error message on Windows 7

### ISSUE THREAD

**Issue by scheidan** [stevengj/Cubature.jl#12]
Thanks for providing this package!

We found that installing `Cubature` on some machines running Windows 7 leads to the following error message:
![image002](https://cloud.githubusercontent.com/assets/3071486/11877828/f83244c2-a4f1-11e5-9a53-276724ce24b6.png)

However, the package seem to be working anyway, only the `installed_vers` file remains empty. 

I think changing this line
https://github.com/stevengj/Cubature.jl/blob/master/deps/build.jl#L26
to
````
run(pipeline(`echo $cubvers`, stdout=tagfile))
``` 
would resolve this issue.

**Comment by stevengj** [comment]
I'll push a patch shortly.  (It would be better to just write the file directly rather than using `echo`.)

**Comment by tkelman** [comment]
The `echo.exe` that we happened to be getting from git is no longer on the path by default in the Windows binaries. @scheidan do report this if you see anything similar in any other packages, feel free to ping me and I'm happy to help fix any issues if needed.

**Comment by scheidan** [comment]
Thanks for the quick fix and the explanation!
