### ISSUE TITLE
build error because of SDE dependence

### ISSUE THREAD

**Issue by CNOT** [stevengj/Cubature.jl#15]
Recently when I tried to update and build Cubature with `Pkg.update()` and `Pkg.build("Cubature")` I got a build error:

    gzip: stdin: unexpected end of file
    tar: Unexpected EOF in archive
    tar: Unexpected EOF in archive
    tar: Error is not recoverable: exiting now
    ==============================[ ERROR: Cubature ]============================

    LoadError: failed process: Process(`tar xzf cubature-1.0.2.tar.gz --directory=.`, ProcessExited(2)) [2]
    while loading ~/.julia/v0.5/Cubature/deps/build.jl, in expression starting on line 17

    =============================================================================

    =============================[ BUILD ERRORS ]==============================

    WARNING: Cubature had build errors.

     - packages with build errors remain installed in /home/sayed/.julia/v0.5
     - build the package(s) and all dependencies with `Pkg.build("Cubature")`
     - build a single package by running its `deps/build.jl` script

    ==========================================================================

Or when I try to run a simple code I get:

    using Cubature
    hcubature(x->x^2,0,2)
    ERROR: error compiling cubature: could not load library "~/.julia/v0.5/Cubature/src/../deps/libcubature"
    ~/.julia/v0.5/Cubature/src/../deps/libcubature: cannot open shared object file: No such file or directory in hcubature at ~/.julia/v0.5/Cubature/src/Cubature.jl:227

So I checked this page, and it says Cubature passes the build tests. Then I checked the dependencies with `Pkg.dependents("Cubature")` which gives: 

    2-element Array{AbstractString,1}:
     "SDE"            
     "KernelEstimator"

and [SDE](https://travis-ci.org/mschauer/SDE.jl) fails the build test.

Because I have some amount of code which uses cubature, what is a temporary work around for this problem?

version:

    Version 0.5.0-dev+433 (2015-09-29 15:39 UTC)
    Commit e60fd18 (103 days old master)
    x86_64-linux-gnu

**Comment by stevengj** [comment]
SDE depends on Cubature, not the other way around.  So, an SDE build failure shouldn't affect the cubature package.

I just tried it on Debian and it works.  Maybe it was just a temporary hiccup in the server?  Just try `Pkg.build("Cubature")` again.

**Comment by CNOT** [comment]
Apparently it was a server hiccup. I downgraded to Julia 0.4 and built Cubature again and it worked. Thanks
