### ISSUE TITLE
host source/binary downloads on another server?

### ISSUE THREAD

**Issue by maxhgerlach** [stevengj/Cubature.jl#20]
Both yesterday and today the ab-initio.mit.edu server was awfully slow, making it impossible to download the file cubature-1.0.2.tar.gz when installing this package. This is GPLed code, so I believe it should be fine to just mirror the file here on Github and use that link when installing the package.

**Comment by stevengj** [comment]
Seems to have been a temporary glitch — the download works fine for me now.  In the longer run, however, it might be nice to move the downloads to another server, e.g. bintray.

**Comment by maxhgerlach** [comment]
That would be a very good idea to improve reliable availability. I had a very hard time locating the cubature source files elsewhere online.

**Comment by pabloferz** [comment]
I'm also having a hard time downloading the `cubature-1.0.2.tar.gz` file. So +1 to moving it to another server.

**Comment by stevengj** [comment]
I just transferred everything to github (https://github.com/stevengj/cubature), docs and all, and have updated the build script.  Will tag a new release once tests are green.
