### ISSUE TITLE
Cubature.jl is broken on Julia 0.6

### ISSUE THREAD

**Issue by giordano** [stevengj/Cubature.jl#22]
`Cubature.jl` is currently broken on Julia master, probably due to https://github.com/JuliaLang/julia/pull/17057.  See [the log](http://pkg.julialang.org/logs/Cubature_0.6.log) from package evaluator:

```
ERROR: LoadError: MethodError: no method matching quad_tst1(::Array{Float64,1})
The applicable method may be too new: running in world age 20394, while current world is 20395.
Closest candidates are:
  quad_tst1(::Any) at /home/vagrant/.julia/v0.6/Cubature/test/runtests.jl:10 (method too new to be called from this world context.)
 in (::Cubature.##17#18{Bool,Bool,Int64,Float64,Float64,Int64,Int32,Int64})() at /home/vagrant/.julia/v0.6/Cubature/src/Cubature.jl:208
 in disable_sigint at ./c.jl:326 [inlined]
 in cubature(::Bool, ::Bool, ::Bool, ::Bool, ::Int64, ::Function, ::Array{Float64,1}, ::UnitRange{Int64}, ::Float64, ::Float64, ::Int64, ::Int32) at /home/vagrant/.julia/v0.6/Cubature/src/Cubature.jl:162
 in #hcubature#22(::Float64, ::Float64, ::Int64, ::Function, ::Function, ::Array{Float64,1}, ::UnitRange{Int64}) at /home/vagrant/.julia/v0.6/Cubature/src/Cubature.jl:223
 in (::Cubature.#kw##hcubature)(::Array{Any,1}, ::Cubature.#hcubature, ::Function, ::Array{Float64,1}, ::UnitRange{Int64}) at ./<missing>:0
 in macro expansion; at /home/vagrant/.julia/v0.6/Cubature/test/runtests.jl:15 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:532
 in include(::String) at ./sysimg.jl:14
 in process_options(::Base.JLOptions) at ./client.jl:293
 in _start() at ./client.jl:357
while loading /home/vagrant/.julia/v0.6/Cubature/test/runtests.jl, in expression starting on line 11
```

Error reported on [discourse](https://discourse.julialang.org/t/help-with-solving-a-world-age-error-in-package-on-julia-master/1126/5?u=giordano), but got no solution.  I'm interested also because `Cuba.jl` is broken as well, for the same exact reason ;-)

**Comment by stevengj** [comment]
Yes, this is a known problem; see the linked Julia issue; I have a PR in Julia to make this a bit easier to fix.

**Comment by giordano** [comment]
Is this fixed with pull request #23?  `master` branch of the package now works with Julia 0.6.

**Comment by stevengj** [comment]
Yes, should be fixed now.

**Comment by giordano** [comment]
Thank you.  I'd like to fix `Cuba.jl` as well, but reading the pull request above I can't understand how to do it, I'm not even sure the same fix applies to my package.  Any hint would be appreciated :-)

**Comment by stevengj** [comment]
I'm hoping @yuyichao and I can update the blog post on callback functions at some point, though I think he was hoping for another issue to be fixed first?
