### ISSUE TITLE
Error compiling cubature : could not load library "libcubature"

### ISSUE THREAD

**Issue by Kolaru** [stevengj/Cubature.jl#27]
Hi there,

I recently tried to use Cubature, but I got that error, which appears when I try to use a function of the package (it has been installed and imported without raising any error).

```
LoadError: error compiling cubature: error compiling #17: could not load library "C:\Users\Benoit\.julia\v0.5\Cubature\src\..\deps\libcubature"
%1 is not a valid Win32 application.

while loading C:\Users\Benoit\Documents\Université\Master Project\test.jl, in expression starting on line 18
 in #hcubature#22(::Float64, ::Int64, ::Int64, ::Function, ::Function, ::Array{Float64,1}, ::Array{Float64,1}) at Cubature.jl:232
 in hcubature(::Function, ::Array{Float64,1}, ::Array{Float64,1}) at Cubature.jl:232
 in include_string(::String, ::String) at loading.jl:441
 in include_string(::Module, ::String, ::String) at eval.jl:32
 in (::Atom.##59#62{String,String})() at eval.jl:73
 in withpath(::Atom.##59#62{String,String}, ::String) at utils.jl:30
 in withpath(::Function, ::String) at eval.jl:38
 in macro expansion at eval.jl:71 [inlined]
 in (::Atom.##58#61{Dict{String,Any}})() at task.jl:60
```

I am using Windows 8 and the Juno package for Atom to run Julia.
I tried to reinstalled the package but nothing changed.

Mysteriously (for me at least), if I try `Pkg.build("Cubature")`, I get
```
INFO: Cubature 1.0.2 is already installed.
```
which is strange since `Pkg.status()` tell me that my version of Cubature is `1.2.1`.

That's it, thanks for both your attention and the package.

**Comment by stevengj** [comment]
1.0.2 is the version of the shared library (DLL).  1.2.1 is the version number of the Julia wrappers.

Try
```
rm(Pkg.dir("Cubature","deps","installed_vers"))
Pkg.build("Cubature")
```
to force it to re-download the library.

**Comment by Kolaru** [comment]
It worked, thank you very much !
