### ISSUE TITLE
Example for hcubature_v / pcubature_v?

### ISSUE THREAD

**Issue by rongar9** [stevengj/Cubature.jl#29]
Would it be possible to get an example for the `_v` integration routines? 

Alternatively, is there a way to "retrieve", as an array, the points where the integrand was evaluated (and the corresponding integrand values)?

**Comment by stevengj** [comment]
There is an example in the test script: https://github.com/stevengj/Cubature.jl/blob/7ebc6bbed8aec1a5a7da84b16048e6a60db0c585/test/runtests.jl#L43-L52

Even with `hcubature_v`, it calls your integrand multiple times.  If you want to keep track of where the integrand was evaluated, just store it in an array.  e.g.:
```jl
function myintegrand(x, xsave)
    push!(xsave, x)
    return sin(3x + 2*cos(4x))
end
xsave = Float64[]
hquadrature(x -> myintegrand(x, xsave), 0, 2, abstol=1e-8)
```
stores the quadrature points in `xsave`.

The `_v` routines are mainly useful if you can parallelize the integrand evaluations.

**Comment by stevengj** [comment]
(A pull request to add an example to the README would be welcome.)

**Comment by rongar9** [comment]
thanks!
