### ISSUE TITLE
Example of bivariate integration over semi-infinite domain

### ISSUE THREAD

**Issue by lewis500** [stevengj/Cubature.jl#32]
Hi I was wondering if you could give an example of how to do the change-of-varaibles trick for integrating a function of two variables over a semi-infinite domain? I read this http://ab-initio.mit.edu/wiki/index.php/Cubature#Infinite_intervals but wasn't sure if I could just repeated the procedure for two variables. I am trying to integrate a joint probability distribution; it happens to be a lognormal. Here is what I did:

```
  qdp(p) =hcubature(x-> begin
    l = x[2]/(1-x[2])
    ɛ = x[1]/(1-x[1])
    if l*p>ɛ
      return 0
    end
    l*f(ɛ,l)/((1-x[1])*(1-x[2]))^2
  end, [0,0],[1,1])[1]
```

**Comment by stevengj** [comment]
Yes, just doing it for two variables is fine.   Alternatively, you could use polar coordinates.

**Comment by stevengj** [comment]
Note that
```jl
if l*p>ɛ
      return 0
end
```
creates a discontinuity, which will greatly slow convergence.  If you want a triangular domain, just do a change of variables in (l, ɛ) coordinates (which is what this is), just do a change of variables to map it to a box as explained e.g. here stevengj/HCubature.jl#16
