### ISSUE TITLE
New updates to Julia 1.0.0

### ISSUE THREAD

**Issue by xuedong** [stevengj/Cubature.jl#39]
Hello guys, do you have any plan to adapt your code to the newest Julia 1.0.0?

**Comment by jmarcellopereira** [comment]
Me too want.

**Comment by kdomino** [comment]
I found HCubature fir Julia 1.0

**Comment by tcporco** [comment]
It still seems to mandate Julia 0.7 and can't be installed on current Julia.

**Comment by xuedong** [comment]
Guys, you can use HCubature instead I guess, closing the issue.
