### ISSUE TITLE
Simple integration over sin(x) fails

### ISSUE THREAD

**Issue by xiaoweiz** [stevengj/Cubature.jl#8]
I'm on Ubuntu 14.04 with Julia 0.3.5. I got interested with [this thread](https://groups.google.com/forum/#!topic/julia-users/ogdfTrT8geg) on Julia user group, in which the OP was using `quadgd` to do integration. I tried `Cubature` and the results were even odder. Am I missing something here

```julia
pquadrature(x -> sin(x), 0, pi)
(1.9999999999999998,2.6597646307635614e-9)
```
is normally executed. But 
```julia
pquadrature(x -> sin(x), 0, 2*pi)
ERROR: hcubature error 1
 in cubature at /home/xiaoweiz/.julia/v0.3/Cubature/src/Cubature.jl:203
 in pquadrature at /home/xiaoweiz/.julia/v0.3/Cubature/src/Cubature.jl:220
```
fails, and 
```julia
hquadrature(x -> sin(x), 0, 2*pi)
```
kills Julia kenel with 
```shell
[1]    2642 bus error (core dumped)  julia
```

**Comment by xiaoweiz** [comment]
I saw the answer to [the thread](https://groups.google.com/forum/#!topic/julia-users/ogdfTrT8geg). Sorry for not reading the introduction of the package carefully.

**Comment by stevengj** [comment]
I should probably set a default `maxvals`, like `quadgk`, so that it `hquadrature` does not keep running until all the memory is exhausted...

But yes, you do need to specify an `abstol` in this kind of case.

**Comment by xiaoweiz** [comment]
Maybe some sort of warning in the case that the function terminates because `maxvals` is reached, like Matlab, so users may know something is wrong?
